export const ERROR_KEYS = {
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  IMAGE_REQUIRED: "IMAGE_REQUIRED",
  UNSUPPORTED_IMAGE_FORMAT: "UNSUPPORTED_IMAGE_FORMAT",
  IMAGE_TOO_LARGE: "IMAGE_TOO_LARGE",
  IMAGE_UPLOAD_FAILED: "IMAGE_UPLOAD_FAILED",

  POST_NOT_FOUND: "POST_NOT_FOUND",
  POST_NO_CONTENT: "POST_NO_CONTENT",
  MISSING_REQUIRED_FIELDS: "MISSING_REQUIRED_FIELDS",
  INVALID_TAGS: "INVALID_TAGS",
  POST_CREATE_FAILED: "POST_CREATE_FAILED",
  POST_UPDATE_FAILED: "POST_UPDATE_FAILED",
  POST_DELETE_FAILED: "POST_DELETE_FAILED",
  COMMENT_CREATE_FAILED: "COMMENT_CREATE_FAILED",
  COMMENT_UPDATE_FAILED: "COMMENT_UPDATE_FAILED",
  COMMENT_DELETE_FAILED: "COMMENT_DELETE_FAILED",
  NO_PERMISSION: "NO_PERMISSION",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  COMMENT_NOT_FOUND: "COMMENT_NOT_FOUND",
  INVALID_IMAGE_FORMAT: "INVALID_IMAGE_FORMAT",
} as const;

export const ERROR_CODES = {
  [ERROR_KEYS.INTERNAL_SERVER_ERROR]: 500,
  [ERROR_KEYS.BAD_REQUEST]: 400,
  [ERROR_KEYS.UNAUTHORIZED]: 401,
  [ERROR_KEYS.FORBIDDEN]: 403,
  [ERROR_KEYS.NOT_FOUND]: 404,

  [ERROR_KEYS.IMAGE_REQUIRED]: 600,
  [ERROR_KEYS.UNSUPPORTED_IMAGE_FORMAT]: 601,
  [ERROR_KEYS.IMAGE_TOO_LARGE]: 602,
  [ERROR_KEYS.IMAGE_UPLOAD_FAILED]: 603,
  [ERROR_KEYS.INVALID_IMAGE_FORMAT]: 604,

  [ERROR_KEYS.POST_NOT_FOUND]: 501,
  [ERROR_KEYS.POST_NO_CONTENT]: 502,
  [ERROR_KEYS.MISSING_REQUIRED_FIELDS]: 502,
  [ERROR_KEYS.INVALID_TAGS]: 503,
  [ERROR_KEYS.POST_CREATE_FAILED]: 504,
  [ERROR_KEYS.POST_UPDATE_FAILED]: 505,
  [ERROR_KEYS.POST_DELETE_FAILED]: 506,
  [ERROR_KEYS.COMMENT_CREATE_FAILED]: 701,
  [ERROR_KEYS.COMMENT_UPDATE_FAILED]: 702,
  [ERROR_KEYS.COMMENT_DELETE_FAILED]: 703,
  [ERROR_KEYS.COMMENT_NOT_FOUND]: 704,

  [ERROR_KEYS.NO_PERMISSION]: 704,
  [ERROR_KEYS.USER_NOT_FOUND]: 705,
} as const;

export const ERROR_MESSAGES = {
  [ERROR_KEYS.BAD_REQUEST]: "잘못된 요청입니다",
  [ERROR_KEYS.FORBIDDEN]: "권한이 없습니다",
  [ERROR_KEYS.UNAUTHORIZED]: "인증에 실패했습니다",
  [ERROR_KEYS.NOT_FOUND]: "리소스를 찾을 수 없습니다",
  [ERROR_KEYS.USER_NOT_FOUND]: "사용자를 찾을 수 없습니다",

  [ERROR_KEYS.POST_NOT_FOUND]: "게시글을 찾을 수 없습니다",
  [ERROR_KEYS.POST_NO_CONTENT]: "게시글 내용을 찾을 수 없습니다",
  [ERROR_KEYS.POST_CREATE_FAILED]: "게시글을 생성할 수 없습니다",
  [ERROR_KEYS.POST_UPDATE_FAILED]: "게시글을 수정할 수 없습니다",
  [ERROR_KEYS.POST_DELETE_FAILED]: "게시글을 삭제할 수 없습니다",

  [ERROR_KEYS.COMMENT_NOT_FOUND]: "댓글을 찾을 수 없습니다",
  [ERROR_KEYS.COMMENT_CREATE_FAILED]: "댓글을 생성할 수 없습니다",
  [ERROR_KEYS.COMMENT_UPDATE_FAILED]: "댓글을 수정할 수 없습니다",
  [ERROR_KEYS.COMMENT_DELETE_FAILED]: "댓글을 삭제할 수 없습니다",
  [ERROR_KEYS.NO_PERMISSION]: "수정/삭제 권한이 없습니다",
  [ERROR_KEYS.IMAGE_UPLOAD_FAILED]: "이미지 업로드에 실패했습니다",
  [ERROR_KEYS.INVALID_IMAGE_FORMAT]: "유효하지 않은 이미지 형식입니다",
  [ERROR_KEYS.IMAGE_REQUIRED]: "이미지 파일이 필요합니다",
  [ERROR_KEYS.UNSUPPORTED_IMAGE_FORMAT]:
    "지원되지 않는 이미지 형식입니다. JPG, PNG, WEBP, GIF 형식만 허용됩니다.",
  [ERROR_KEYS.IMAGE_TOO_LARGE]: "이미지 크기가 너무 큽니다. 최대 10MB까지 허용됩니다.",
  [ERROR_KEYS.MISSING_REQUIRED_FIELDS]: "제목과 내용은 필수 항목입니다",
  [ERROR_KEYS.INVALID_TAGS]: "유효하지 않은 태그 형식입니다",
} as const;
