name: Deploy to Oracle Cloud

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.OCI_SSH_PRIVATE_KEY }}

      - name: Run Deployment
        run: |
          ssh -o StrictHostKeyChecking=no opc@${{ secrets.OCI_INSTANCE_IP }} << 'DEPLOY'
          cd /root/projects/cocomomo-backend
          git pull origin main
          pnpm install --prod
          [ -f .env ] || cp .env.production .env
          
          if pm2 list | grep -q "cocomomo-backend"; then
            pm2 restart cocomomo-backend
          else
            pm2 start dist/main.js --name cocomomo-backend --max-memory-restart 300M
          fi
          
          pm2 save
          DEPLOY