name: Deploy to Oracle Cloud

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.OCI_SSH_PRIVATE_KEY }}
      - name: Setup SSH known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.OCI_INSTANCE_IP }} $(ssh-keyscan -t rsa ${{ secrets.OCI_INSTANCE_IP }} 2>/dev/null)" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
      - name: Run Deployment
        env:
          SERVER_IP: ${{ secrets.OCI_INSTANCE_IP }}
        run: |
          if [ -z "$SERVER_IP" ]; then
            echo "Error: OCI_INSTANCE_IP is not set in GitHub Secrets"
            exit 1
          fi
          ssh opc@$SERVER_IP << 'DEPLOY'
          cd /home/opc/cocomomo-backend
          git pull origin main
          pnpm install
          NODE_OPTIONS="--max-old-space-size=4096" pnpm build
          
          if pm2 list | grep -q "cocomomo-backend"; then
            pm2 restart cocomomo-backend
          else
            pm2 start dist/main.js --name cocomomo-backend --max-memory-restart 300M
          fi
          pm2 save
          DEPLOY